In [1]:
import numpy as np
a_20 = np.array ([0,1,2,3,4])
print(a_20)

[0 1 2 3 4]


In [2]:
import numpy as np
# Membuat array NumPy
arr1 = np.array([[2, 4, 6], [1, 3, 5]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
# Menampilkan array
print("Array pertama:")
print(arr1)
print("\nArray kedua:")
print(arr2)
# Operasi penjumlahan
result_add = np.add(arr1, arr2)
print("\nHasil Penjumlahan:")
print(result_add)
# Operasi pengurangan
result_subtract = np.subtract(arr1, arr2)
print("\nHasil Pengurangan:")
print(result_subtract)
# Operasi perkalian
result_multiply = np.multiply(arr1, arr2)
print("\nHasil Perkalian:")
print(result_multiply)
# Operasi pembagian
result_divide = np.divide(arr1, arr2)
print("\nHasil Pembagian:")
print(result_divide)
# Operasi perkalian matriks
matrix_product = np.dot(arr1, arr2.T)  
print("\nHasil Perkalian Matriks:")
print(matrix_product)

Array pertama:
[[2 4 6]
 [1 3 5]]

Array kedua:
[[ 7  8  9]
 [10 11 12]]

Hasil Penjumlahan:
[[ 9 12 15]
 [11 14 17]]

Hasil Pengurangan:
[[-5 -4 -3]
 [-9 -8 -7]]

Hasil Perkalian:
[[14 32 54]
 [10 33 60]]

Hasil Pembagian:
[[0.28571429 0.5        0.66666667]
 [0.1        0.27272727 0.41666667]]

Hasil Perkalian Matriks:
[[100 136]
 [ 76 103]]
